### ISSUE TITLE
Captcha input verification fail... 

### ISSUE THREAD

**Issue by pvbedadur** [cowinapi/developer.cowin#106]
Captcha input verification fails on several occasions. 
Even if user enters the correct CAPTCHA... Website declares it as wrong... 
If slots aren't available....user should be notified with correct information...instead website displays captcha incorrect... And captcha refreshes... 
The incorrect information confuses users...

**Comment by shailesh21** [comment]
Captcha is really hard to enter. Here is what I have faced:
1. Captcha box doesn't shows any typed text inside. And is really not human friendly
2. Captcha show error even if I enter correct captcha and I am sure because I mostly lose slot because of slow captcha typing.

tbh, experience is really frustrating and not human friendly.

**Comment by manojagarwal68** [comment]
Yeah, captcha is failing a number of times before it succeeds. This implementation is messed up.
