### ISSUE TITLE
Please remove current stupid captcha and use Recaptcha by Google Simple. And Straight

### ISSUE THREAD

**Issue by siddhesh1770** [cowinapi/developer.cowin#159]
Because of that tricky captcha I lost my booking

**Comment by rudrasura** [comment]
Bro, even if you could have got the captcha right, server responds with 504!

**Comment by rudrasura** [comment]
![during_booking](https://user-images.githubusercontent.com/8121382/117811907-be1b0f80-b27e-11eb-8ac5-0c05b6dfd6fb.png)
Look at this!
This issue is persistent with multiple people!

**Comment by test2a** [comment]
Id say not using recaptcha is a good thing because 1. Google now charges outrageous fees for using that ( hcaptcha seems  much cheaper)
2. We should not "just" accept Google in each and every web property because its slightly convenient.

Why not ask instead the captcha be changed to say numbers only or much less difficulty or something else? First party implementation is preferred when you have a private transaction (vaccination) which shouldnt be online in the first place but now that its being forced upon us, why not minimize exposure?

**Comment by siddhesh1770** [comment]
Yeah That will do too

**Comment by sekadiv** [comment]
please remove this captcha while booking as it is not inclusive design and by accessibility

**Comment by nileshruby** [comment]
captcha cause issue it's not booking since last 3 days any slot.
