### ISSUE TITLE
Few telegram bots always detect slots 5-8 minutes earlier than my Polling  scripts

### ISSUE THREAD

**Issue by ritesh-nitw** [cowinapi/developer.cowin#184]
I am trying to figure out the reason behind the inconsistency. 
I know that the data can be cached for 30 minutes but how few of the telegram bots **always** find the availability 5-8 minutes earlier than the polling script I am running at AWS Mumbai instance:
- Polling time is 6 seconds.
- Endpoint used is /v2/appointment/sessions/public/calendarByDistrict

   Date Passed= today's date
 
   District id= < Only one district id passed >
   
Did anyone notice this behaviour? 

Is there an end point that is updated earlier than the above endpoint?

**Comment by DnyaneshwarShiv** [comment]
Yes.Even I am facing same. not sure why this is happening

**Comment by abizerlokhandwala** [comment]
From my experiments, `calendarByDistrict` is heavily cached while `findByDistrict` has a shorter/no cache. My scripts are running every 10 seconds and I am able to detect slots a few seconds earlier than the Telegram Bots (probably because I am using emails for notifications).

You can check out project here: https://vaccinepost.co.in/
If you'd like to contribute, do come along here and help us out!
Frontend: https://github.com/Guzzler/Cowin-Notification-Service
Backend: https://github.com/abizerlokhandwala/Cowin-Notification-Service

**Comment by ritesh-nitw** [comment]
> From my experiments, `calendarByDistrict` is heavily cached while `findByDistrict` has a shorter/no cache. My scripts are running every 10 seconds and I am able to detect slots a few seconds earlier than the Telegram Bots (probably because I am using emails for notifications).
> 
> You can check out project here: https://vaccinepost.co.in/
> If you'd like to contribute, do come along here and help us out!
> Frontend: https://github.com/Guzzler/Cowin-Notification-Service
> Backend: https://github.com/abizerlokhandwala/Cowin-Notification-Service
