### ISSUE TITLE
under what circumstances are centers adding just 1 dose-1?

### ISSUE THREAD

**Issue by nikhiltalreja** [cowinapi/developer.cowin#341]
I notice that centers add just one dose-1 capacity at times. Can anyone explain this scenario?

**Comment by sikander441** [comment]
Maybe someone cancelled and a slot became available.

**Comment by theGeekyLad** [comment]
> Maybe someone cancelled and a slot became available.

I'd second that since I've been seeing a lot of this one-slot-never-books occurrence. Indeed, the booking never passes through, at least for me.

**Comment by harshit-sh** [comment]
> Maybe someone cancelled and a slot became available.

Right, I'm guessing this happens when a person chooses a slot in a different centre after booking a slot in the same booking window. For someone else to book this slot, I had created this issue for the UI to filter out the slots which are completely booked for better access: https://github.com/cowinapi/developer.cowin/issues/230

> Indeed, the booking never passes through, at least for me.

That probably happens because someone else has already booked it before you since a few seconds later the centre shows the status as 'booked'
