### ISSUE TITLE
[Umang] Is the slot information legit?

### ISSUE THREAD

**Issue by theGeekyLad** [cowinapi/developer.cowin#366]
To anyone here that uses Umang instead of the CoWIN portal, is the slot information updated in real-time?

I understand that Umang uses it's own set of APIs to access slot data (maybe a BFF atop CoWIN) but, from your experience, is the data cached like those displayed on the CoWIN home page (when you're not logged in) ?

**Comment by karsumit94** [comment]
I guess the Umang and the Arogya Setu vaccination process uses the same public API that is used in the CoWin Website front page. And it has cached data.

**Comment by theGeekyLad** [comment]
@karsumit94 I can confirm the opposite as I've seen network requests (in the browser network tab) for slot data as well as booking being made to their homegrown endpoints.

Nonetheless, you maybe right as it's quite likely that their slot-search API is, in reality, a BFF to the CoWIN's public slot-search API. Nonetheless, would like to confirm the validity.

**Comment by dileepps** [comment]
Public API from Cowin gives only cached data, so may not be very accurate. Once after login you get exact availability details.
I have used Public Api and developed a site for statistical analysis. http://dreamninja.shop/cowin/
I find it very difficult to use Private API's due to OTP validation and also restrictions in number of calls.
