### ISSUE TITLE
Click on open slot before login to take one to booking

### ISSUE THREAD

**Issue by muniamma** [cowinapi/developer.cowin#55]
Presently, one can search before logging in to find out centers with open slots. Would be good if clicking on the slot, one is taken to the booking directly (after login credentials) instead of agiain having to login and do a search.

**Comment by riteshpanjwani** [comment]
Logged out search results show 30 minutes old cached data and use public APIs
Logged in search results show real time data and use protected APIs
Because of this, there's not much point having this feature.
Correct me if I am wrong on this.

I am not a developer at Co-WIN, but this is what I have observed.

**Comment by muniamma** [comment]
I am a user. For me the information has to be consistent. I am not bothered
about your caching or how you implement.

G Padmanabhan

**Comment by riteshpanjwani** [comment]
Even I am an user. And sadly, it is not consistent.
